import assert from 'node:assert/strict';
globalThis.window={};
const wallet=await import('./dist/wallet.js');
await assert.rejects(wallet.connectNoir,/Noir was not detected/);
assert.equal(await wallet.restoreNoir(),null);
const requests=[];
window.noirwallet={zcash:{request:async({method})=>{requests.push(method);return {shielded:'u1_test_account'};}}};
assert.equal((await wallet.connectNoir()).shielded,'u1_test_account');
assert.equal((await wallet.restoreNoir()).shielded,'u1_test_account');
await wallet.disconnectNoir();
assert.deepEqual(requests,['zcash_requestAccounts','zcash_getAccounts','zcash_disconnect']);
window.noirwallet.zcash.request=async()=>{throw {code:4001};};
await assert.rejects(wallet.connectNoir,/declined/);
window.noirwallet.zcash.request=async()=>null;
await assert.rejects(wallet.connectNoir,/No shielded account/);
assert.equal(await wallet.restoreNoir(),null);
console.log('Wallet contract checks passed: absent extension, approved connection, restore, disconnect, rejection and empty account. No payment RPCs.');
